---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: uuid-generator-php
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: kdihalas/knative-php-example:latest
