name: knative-nodejs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker-login
      uses: "actions/docker/login@master"
      env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: build
      uses: crswty/buildpack-action@master
      env:
        PUBLISH: true
        IMAGE_NAME: kdihalas/knative-nodejs-example:latest
        BUILDER: cloudfoundry/cnb:bionic
