name: knative-python
on:
  push:
    paths:
    - 'python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker-login
      env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: build
      run: docker build ./python/ -t kdihalas/knative-python-example:latest
    - name: push
      run: docker push kdihalas/knative-python-example:latest
